name: create-release
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npx nx run-many -t lint
      - name: Test
        run: npx nx run-many -t test --configuration=ci
      - name: Build
        run: npx nx run-many -t build
      - name: E2E Tests
        run: npm run test
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
